### ISSUE TITLE
Set up initial GitHub action for performance tests

### ISSUE THREAD

**Issue by mukeshpanchal27** [10up/wordpress-develop#2]
- Add new GitHub action called "performance.yml"
- Create a docker environment
- WordPress core has already setup the docker environment that we can reuse. https://github.com/WordPress/wordpress-develop/tree/trunk/.github/workflows

### Acceptance Criteria

- Create `performance.yml` GitHub workflows in the `.github/workflows/` folder.
- Add workflow name: `Performance Tests`
- Specifies the trigger for the workflow: In our case it will trigger on `push` event
- Add job name: `performance`
- Add job runner: `ubuntu-latest`
- Job run condition: 
   - It will only run if the repository is `WordPress/wordpress-develop` and on `push` event. Otherwise, the job will be marked as skipped.
- Add steps:
   -  Add `actions/checkout` action
   - Add `actions/setup-node` and use `.nvmrc` file for node version.
   - Setup node
      - `npm ci`
   - Docker debug information
      - `docker -v`
      - `docker-compose -v`
   - Start Docker environment
      - `npm run env:start`
   - Install WordPress
      - `npm run env:install`

Add placeholder job `npm run test:performance` that writing some logging output, which we can enhance in a future ticket with a working test script.

**Comment by mukeshpanchal27** [comment]
@joemcgill @felixarntz  AC ready for review.

**Comment by joemcgill** [comment]
Thanks @mukeshpanchal27. I'd suggest we rename this ticket to focus on the fact that you're adding a new performance github action, rather than the docker environment, which seems more like an implementation detail. Something like "Set up initial GitHub action for performance tests".

We should specify when this job should run. I'd suggest we follow the convention used by other actions, like [the E2E tests](https://github.com/WordPress/wordpress-develop/blob/trunk/.github/workflows/end-to-end-tests.yml#L52).

I also think we could go ahead and include a placeholder job for running these tests like `npm run test:performance` that does nothing for now other than maybe writing some logging output, which we can enhance in a future ticket with a working test script.

Does that all make sense?

**Comment by mukeshpanchal27** [comment]
Thanks @joemcgill for the review. Yes, that makes sense. I have addressed it and updated the AC's details. Thanks!

**Comment by joemcgill** [comment]
Looks good to me. Thanks, @mukeshpanchal27!

**Comment by adamsilverstein** [comment]
Looks good!

Do we need to add a step to install and activate the mu server timing plugin (or is that covered elsewhere)?

edit: NM I see that is covered in https://github.com/10up/wordpress-develop/issues/4

**Comment by eclarke1** [comment]
It looks as though this AC is approved, so moving over to 'To Do' to signify it is ready for work.

**Comment by eclarke1** [comment]
Currently assigned to @felixarntz to review this, but once reviewed, he can be unassigned and work commenced.

**Comment by felixarntz** [comment]
Thanks all, ACs look good to me! ✅

**Comment by mukeshpanchal27** [comment]
@joemcgill Can i mark this issue closed?

**Comment by joemcgill** [comment]
Yep, this was resolved by #6. Closing.
